steps:
- name: 'gcr.io/cloud-builders/docker'  # Use the official Docker builder image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-model', './model']  # Build the model container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-web-server', './web-server']  # Build the web server container
# Add steps to push the images to Google Container Registry and deploy to Cloud Run if needed
images:
- 'gcr.io/$PROJECT_ID/my-model'
- 'gcr.io/$PROJECT_ID/my-web-server'
