steps:
- name: 'gcr.io/cloud-builders/docker'  # Use the official Docker builder image
  args: 
    - 'build'
    - '-t' 
    - 'gcr.io/$PROJECT_ID/my-model'
    - './model'  # Build the model container, assuming Dockerfile is in the 'model' directory
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/my-web-server' 
    - './web-server'  # Build the web server container, assuming Dockerfile is in the 'web-server' directory

# Add steps to push the images to Google Container Registry and deploy to Cloud Run
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-model']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-web-server']

# Example deployment steps (adjust as needed)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'my-web-server-service' # Replace with your desired service name
  - '--image=gcr.io/$PROJECT_ID/my-web-server'
  - '--platform=managed'
  - '--region=us-central1' # Or your preferred region
  - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/my-model'
- 'gcr.io/$PROJECT_ID/my-web-server'
